# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeliveryServiceDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryServiceDemo

  pod 'GoogleMaps'
  pod 'ReachabilitySwift'



  target 'DeliveryServiceDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeliveryServiceDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
